"""Jobs (§2, §6): row → ``JobStatus``, the storage layout, event streaming and result
packaging shared by every backend, plus the PostgREST implementation.

Storage layout (§2, §10): ``jobs/<user_id>/<job_id>/`` holds ``input.<ext>``, one
``<stem>.wav`` per stem and ``score.mid``. The job id is generated by ``create_job``, so
``JobsService.create`` receives the *object name* of the input (``input.<ext>``) and the
full key is derived with :func:`input_storage_key` once the row exists.
"""

from __future__ import annotations

import asyncio
from collections.abc import AsyncIterator, Awaitable, Callable, Mapping
from datetime import UTC, datetime, timedelta
from typing import Any, Literal
from uuid import UUID, uuid4

from app.errors import CONFLICT, INTERNAL_ERROR, NOT_FOUND, VALIDATION_ERROR, ApiException
from app.schemas import (
    JobError,
    JobOptions,
    JobResult,
    JobsPage,
    JobStatus,
    PipelineResult,
    ProgressEvent,
)
from app.services import CreditsService, StorageService
from app.services.events import (
    EVENT_ERROR,
    EVENT_PROGRESS,
    EVENT_RESULT,
    TERMINAL_EVENTS,
    JobEvent,
    JobEventBus,
)
from app.services.supabase import Filter, SupabaseClient, all_of, any_of

JOB_CREDITS = 1
"""Credits reserved per job; ``create_job`` reserves exactly this many (§2, §6)."""
SERVER_IDEMPOTENCY_PREFIX = "auto:"
"""Marks a key this service minted because the client sent none (see :meth:`create`)."""
MIDI_FILE = "score.mid"
CANCELLED_ERROR = JobError(code="cancelled", message="The job was cancelled.")
EventsMode = Literal["bus", "poll"]
DEFAULT_POLL_INTERVAL_SECONDS = 1.0
JOB_CURSOR_SEPARATOR = "_"
"""Joins the RFC 3339 timestamp and the job id of a cursor; absent from both."""
_CURSOR_TIMESTAMP_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"


def user_prefix(user_id: UUID) -> str:
    """Storage prefix holding every object of one user (account deletion, §1)."""
    return f"jobs/{user_id}/"


def job_prefix(user_id: UUID, job_id: UUID) -> str:
    return f"jobs/{user_id}/{job_id}"


def input_storage_key(user_id: UUID, job_id: UUID, input_name: str) -> str:
    return f"{job_prefix(user_id, job_id)}/{input_name}"


def input_name_of(record: Mapping[str, Any]) -> str | None:
    meta = record.get("input_meta")
    name = meta.get("input_name") if isinstance(meta, Mapping) else None
    return name if isinstance(name, str) and name else None


def job_status_from_record(record: Mapping[str, Any]) -> JobStatus:
    """A ``jobs`` row (PostgREST JSON or the in-memory equivalent) as ``JobStatus``."""
    error = record.get("error")
    result = record.get("result")
    progress = float(record.get("progress") or 0.0)
    return JobStatus(
        job_id=record["id"],
        status=record["status"],
        stage=record.get("stage") or "upload",
        progress=min(max(progress, 0.0), 1.0),
        created_at=record["created_at"],
        started_at=record.get("started_at"),
        finished_at=record.get("finished_at"),
        error=(
            JobError(
                code=str(error.get("code") or INTERNAL_ERROR),
                message=str(error.get("message") or ""),
            )
            if isinstance(error, Mapping)
            else None
        ),
        result=JobResult.model_validate(result) if isinstance(result, Mapping) else None,
    )


def encode_job_cursor(status: JobStatus) -> str:
    """The ``GET /v1/jobs`` cursor naming the last job of a page. The timestamp is
    rendered in UTC with ``Z`` so the cursor survives a query string unencoded (a ``+``
    would be read back as a space) and keeps its microseconds for the ``eq`` half of
    the keyset condition."""
    stamp = status.created_at.astimezone(UTC).strftime(_CURSOR_TIMESTAMP_FORMAT)
    return f"{stamp}{JOB_CURSOR_SEPARATOR}{status.job_id}"


def parse_job_cursor(cursor: str | None) -> tuple[datetime, UUID] | None:
    """``(created_at, job_id)`` of the last job seen, or ``None`` for the first page;
    anything not produced by :func:`encode_job_cursor` is ``422``."""
    if cursor is None or cursor == "":
        return None
    stamp, separator, raw_id = cursor.partition(JOB_CURSOR_SEPARATOR)
    try:
        if not separator:
            raise ValueError(cursor)
        created_at = datetime.strptime(stamp, _CURSOR_TIMESTAMP_FORMAT).replace(tzinfo=UTC)
        return created_at, UUID(raw_id)
    except ValueError as exc:
        raise ApiException(
            VALIDATION_ERROR,
            details={
                "errors": [
                    {
                        "loc": ["query", "cursor"],
                        "msg": "cursor must be a value returned as next_cursor",
                        "type": "value_error",
                    }
                ]
            },
        ) from exc


def jobs_before(created_at: datetime, job_id: UUID) -> Filter:
    """PostgREST keyset condition for the rows after a cursor in ``created_at desc, id
    desc`` order."""
    return any_of(
        ("created_at", "lt", created_at),
        all_of(("created_at", "eq", created_at), ("id", "lt", str(job_id))),
    )


def jobs_page(rows: list[Mapping[str, Any]], limit: int) -> JobsPage:
    """``rows`` are newest-first and were fetched with ``limit + 1`` to detect a next page."""
    page = [job_status_from_record(row) for row in rows[:limit]]
    next_cursor = encode_job_cursor(page[-1]) if len(rows) > limit and page else None
    return JobsPage(jobs=page, next_cursor=next_cursor)


def without_signed_urls(status: JobStatus) -> JobStatus:
    """The status with every stem and MIDI URL blanked: the account export (§1) carries
    the analysis a job produced but never an object URL."""
    if status.result is None:
        return status
    result = status.result.model_copy(
        update={
            "stems": [stem.model_copy(update={"url": None}) for stem in status.result.stems],
            "midi": status.result.midi.model_copy(update={"url": None}),
        }
    )
    return status.model_copy(update={"result": result})


def progress_event(stage: str, progress: float) -> JobEvent:
    return {
        "event": EVENT_PROGRESS,
        "data": ProgressEvent(stage=stage, progress=progress).model_dump(mode="json"),  # type: ignore[arg-type]
    }


def status_event(status: JobStatus) -> JobEvent:
    """The event describing ``status`` right now: terminal for finished jobs, else progress."""
    if status.status == "succeeded":
        return {"event": EVENT_RESULT, "data": status.model_dump(mode="json")}
    if status.status == "failed":
        error = status.error or JobError(code=INTERNAL_ERROR, message="The job failed.")
        return {"event": EVENT_ERROR, "data": error.model_dump(mode="json")}
    if status.status == "cancelled":
        return {"event": EVENT_ERROR, "data": CANCELLED_ERROR.model_dump(mode="json")}
    return progress_event(status.stage, status.progress)


async def stream_job_events(
    job_id: UUID,
    fetch: Callable[[], Awaitable[JobStatus | None]],
    bus: JobEventBus,
    mode: EventsMode,
    poll_interval: float = DEFAULT_POLL_INTERVAL_SECONDS,
) -> AsyncIterator[JobEvent]:
    """Events for the SSE / WS routes (§2), ending after ``result`` or ``error``.

    ``bus`` mode subscribes to the in-process bus before reading the row so nothing
    published in between is lost; ``poll`` mode re-reads the row every ``poll_interval``
    for deployments where the worker runs in another process.
    """
    missing: JobEvent = {
        "event": EVENT_ERROR,
        "data": {"code": NOT_FOUND, "message": "Job not found."},
    }
    if mode == "bus":
        async with bus.subscription(job_id) as queue:
            status = await fetch()
            if status is None:
                yield missing
                return
            event = status_event(status)
            yield event
            if event["event"] in TERMINAL_EVENTS:
                return
            while True:
                event = await queue.get()
                yield event
                if event["event"] in TERMINAL_EVENTS:
                    return
    last: tuple[str, float] | None = None
    while True:
        status = await fetch()
        if status is None:
            yield missing
            return
        event = status_event(status)
        if event["event"] in TERMINAL_EVENTS:
            yield event
            return
        key = (status.stage, status.progress)
        if key != last:
            last = key
            yield event
        await asyncio.sleep(poll_interval)


async def package_result(
    job_id: UUID,
    user_id: UUID,
    result: PipelineResult,
    *,
    storage: StorageService,
    credits: CreditsService,
    signed_url_ttl_seconds: int,
) -> JobResult:
    """Upload the stems and the MIDI file under the job's prefix, sign their URLs and
    assemble the §2 ``JobResult``. ``credits_charged`` / ``balance_after`` / ``expires_at``
    are provisional here; ``complete_job`` stores the authoritative values."""
    prefix = job_prefix(user_id, job_id)
    stems = []
    for stem in result.stems:
        if stem.wav_bytes is None:
            raise ValueError(f"stem {stem.name} carries no audio")
        path = f"{prefix}/{stem.name}.wav"
        await storage.upload_bytes(path, stem.wav_bytes, "audio/wav")
        url = await storage.signed_url(path, signed_url_ttl_seconds)
        stems.append(stem.model_copy(update={"url": url, "wav_bytes": None}))
    if result.midi.smf_bytes is None:
        raise ValueError("midi result carries no file")
    midi_path = f"{prefix}/{MIDI_FILE}"
    await storage.upload_bytes(midi_path, result.midi.smf_bytes, "audio/midi")
    midi_url = await storage.signed_url(midi_path, signed_url_ttl_seconds)
    midi = result.midi.model_copy(update={"url": midi_url, "smf_bytes": None})
    balance = await credits.get_balance(user_id)
    return JobResult(
        job_id=job_id,
        credits_charged=JOB_CREDITS,
        balance_after=max(balance.credits - JOB_CREDITS, 0),
        input=result.input,
        analysis=result.analysis,
        stems=stems,
        midi=midi,
        expires_at=datetime.now(UTC) + timedelta(seconds=signed_url_ttl_seconds),
    )


class SupabaseJobsService:
    def __init__(
        self,
        client: SupabaseClient,
        bus: JobEventBus,
        *,
        events_mode: EventsMode = "bus",
        poll_interval: float = DEFAULT_POLL_INTERVAL_SECONDS,
    ) -> None:
        self._client = client
        self._bus = bus
        self._events_mode: EventsMode = events_mode
        self._poll_interval = poll_interval
        self._started: set[UUID] = set()

    async def create(
        self, user_id: UUID, options: JobOptions, input_key: str, credits_reserved: int
    ) -> JobStatus:
        if credits_reserved != JOB_CREDITS:
            raise ValueError("create_job reserves exactly one credit per job")
        # create_job inserts the job and reserves the credit in one transaction, so a
        # replay without a key would charge twice and strand the first job in `queued`
        # forever. Every call therefore carries a key — the client's when it sent one,
        # otherwise a fresh one — which makes the RPC replayable: a repeat returns the
        # job the first attempt created.
        idempotency_key = options.idempotency_key or f"{SERVER_IDEMPOTENCY_PREFIX}{uuid4()}"
        row = await self._client.rpc(
            "create_job",
            {
                "p_user_id": str(user_id),
                "p_options": options.model_dump(mode="json"),
                "p_input_meta": {"input_name": input_key},
                "p_idempotency_key": idempotency_key,
            },
        )
        return job_status_from_record(row)

    async def find_by_idempotency_key(self, user_id: UUID, key: str) -> JobStatus | None:
        rows = await self._client.select(
            "jobs",
            filters=[("user_id", "eq", str(user_id)), ("idempotency_key", "eq", key)],
            limit=1,
        )
        return job_status_from_record(rows[0]) if rows else None

    async def get(self, job_id: UUID, user_id: UUID) -> JobStatus | None:
        rows = await self._client.select(
            "jobs", filters=[("id", "eq", str(job_id)), ("user_id", "eq", str(user_id))], limit=1
        )
        return job_status_from_record(rows[0]) if rows else None

    async def list(self, user_id: UUID, limit: int = 20, cursor: str | None = None) -> JobsPage:
        position = parse_job_cursor(cursor)
        filters: list[Filter] = [("user_id", "eq", str(user_id))]
        if position is not None:
            filters.append(jobs_before(*position))
        rows = await self._client.select(
            "jobs", filters=filters, order="created_at.desc,id.desc", limit=limit + 1
        )
        return jobs_page(rows, limit)

    async def _fetch(self, job_id: UUID) -> JobStatus | None:
        rows = await self._client.select("jobs", filters=[("id", "eq", str(job_id))], limit=1)
        return job_status_from_record(rows[0]) if rows else None

    async def set_progress(self, job_id: UUID, stage: str, progress: float) -> None:
        if job_id not in self._started:
            self._started.add(job_id)
            try:
                await self._client.rpc("start_job", {"p_job_id": str(job_id), "p_worker_ref": None})
            except ApiException as exc:
                if exc.code != CONFLICT:  # finished or cancelled meanwhile: nothing to report
                    raise
                return
        row = await self._client.rpc(
            "update_job_progress",
            {"p_job_id": str(job_id), "p_stage": stage, "p_progress": progress},
        )
        if isinstance(row, Mapping) and row.get("status") == "running":
            self._bus.publish(job_id, EVENT_PROGRESS, progress_event(stage, progress)["data"])

    async def complete(self, job_id: UUID, result: JobResult) -> JobStatus:
        row = await self._client.rpc(
            "complete_job", {"p_job_id": str(job_id), "p_result": result.model_dump(mode="json")}
        )
        return self._finish(job_id, row)

    async def fail(self, job_id: UUID, code: str, message: str) -> JobStatus:
        row = await self._client.rpc(
            "fail_job", {"p_job_id": str(job_id), "p_error": {"code": code, "message": message}}
        )
        return self._finish(job_id, row)

    async def cancel(self, job_id: UUID, user_id: UUID) -> JobStatus:
        row = await self._client.rpc(
            "cancel_job", {"p_job_id": str(job_id), "p_user_id": str(user_id)}
        )
        return self._finish(job_id, row)

    def _finish(self, job_id: UUID, row: Mapping[str, Any]) -> JobStatus:
        status = job_status_from_record(row)
        self._started.discard(job_id)
        event = status_event(status)
        if event["event"] in TERMINAL_EVENTS:
            self._bus.publish(job_id, event["event"], event["data"])
        return status

    def events(self, job_id: UUID) -> AsyncIterator[JobEvent]:
        return stream_job_events(
            job_id, lambda: self._fetch(job_id), self._bus, self._events_mode, self._poll_interval
        )

    async def reap_stale(self, timeout_seconds: int) -> int:
        count = await self._client.rpc("reap_stale_jobs", {"p_timeout_seconds": timeout_seconds})
        return int(count or 0)


__all__ = [
    "CANCELLED_ERROR",
    "DEFAULT_POLL_INTERVAL_SECONDS",
    "JOB_CREDITS",
    "JOB_CURSOR_SEPARATOR",
    "MIDI_FILE",
    "SERVER_IDEMPOTENCY_PREFIX",
    "EventsMode",
    "SupabaseJobsService",
    "encode_job_cursor",
    "input_name_of",
    "input_storage_key",
    "job_prefix",
    "job_status_from_record",
    "jobs_before",
    "jobs_page",
    "package_result",
    "parse_job_cursor",
    "progress_event",
    "status_event",
    "stream_job_events",
    "user_prefix",
    "without_signed_urls",
]
