/* =====================================================================
 * WS1.0 — AI × Jobs Narrative Coding · Google Forms builder (Apps Script)
 *
 * Builds ONE Google Form per coder:
 *   - 300 fragments, ONE fragment per page (no peeking ahead)
 *   - Q1 relevance on every page; Q2 valence on a follow-up page that is
 *     shown ONLY if Q1 = Yes (skip logic, matches CODEBOOK.md)
 *   - fragment order randomised per coder (seeded by CODER — the same seed
 *     rule as ws1_survey.html, so "Anna" gets the same order in both tools)
 *   - answers land in the form's Responses tab (export as CSV, then run
 *     gforms_to_csv.py to get the file ws1_gate.py reads)
 *
 * HOW TO USE (repeat once per coder)
 *   1. script.google.com -> New project -> delete the default code -> paste
 *      this whole file. Save (Ctrl/Cmd+S).
 *   2. Set CODER below (e.g. 'Anna'). Save again.
 *   3. Run ▸ buildForm. The first run asks for permission (Forms + Drive):
 *      allow it, then click Run again.
 *   4. Open "Execution log". Apps Script stops any run at ~6 minutes, so the
 *      builder works in chunks: if the log says "Run buildForm again", run it
 *      again — it resumes exactly where it stopped. 2–4 runs in total.
 *   5. When the log prints DONE it shows two links:
 *        EDIT URL       — yours (look, but do not edit questions)
 *        RESPONDENT URL — send THIS one to the coder
 *   6. Second coder: change CODER, save, Run ▸ buildForm -> a new form with a
 *      different order.
 *
 * OTHER FUNCTIONS
 *   status()         — prints progress + links for the current CODER
 *   resetProgress()  — forgets the build state for CODER (then move the old
 *                      form to Trash in Drive by hand) so buildForm starts over
 *
 * This file is generated by make_gform_script.py from coding_sample.csv.
 * Do not edit the FRAGMENTS block by hand.
 * ===================================================================== */

const CODER = 'Coder_A';   // <<< set per coder, save, then Run ▸ buildForm
const FORM_TITLE = 'WS1.0 — AI × Jobs Narrative Coding';
const TIME_BUDGET_MS = 4.5 * 60 * 1000;   // stay under the ~6 min execution cap

const INTRO = [
  "You will read 300 short fragments (~50 words each) from YouTube transcripts about AI and work. One fragment per page, two questions per fragment. About 45-60 minutes in total.",
  "",
  "RULES",
  "- Code alone. Do not discuss fragments with anyone while coding.",
  "- Judge ONLY the words in the fragment - not the video's overall topic.",
  "- Answer in order, one page at a time. Please do not use the Back button.",
  "- If you are signed in to Google your progress is saved automatically; you can close and continue later.",
  "",
  "Q1 - RELEVANT (Yes / No)",
  "Yes ONLY if the fragment itself contains BOTH an AI/automation word AND a job/occupation word, AND connects them (says something about what AI does to that work). If anything is missing -> No.",
  "",
  "Q2 - VALENCE (asked only when Q1 = Yes)",
  "- Alarming (minus): AI destroys / replaces / shrinks jobs, freezes hiring, lowers wages.",
  "- Reassuring (plus): AI creates / augments jobs - OR the destruction fear is overblown or false (debunking, 'they had to rehire', 'AI costs more than the worker').",
  "- Mixed: both directions, roughly equal weight.",
  "- Neutral / no direction (none): relevant, but no directional claim - a question, background, or doubt about whether AI is really the cause.",
  "",
  "Two rules that decide most hard cases:",
  "1) Debunking destruction = Reassuring (plus), not minus. The vocabulary is not the stance; the stance is what the speaker argues.",
  "2) Doubt about the cause ('was it AI, or just an excuse for cost-cutting?') = Neutral (none), not minus."
].join("\n");

const HELP_REL = "Yes ONLY if THIS fragment has an AI/automation word AND a job/occupation word AND connects them. Do not borrow the video's topic. Anything missing -> No.";
const HELP_VAL = "Alarming (minus): AI destroys/replaces/shrinks jobs.  ·  Reassuring (plus): AI creates/augments jobs, OR the destruction fear is overblown/false (debunking, 'had to rehire', 'AI costs more than the worker').  ·  Mixed: both, roughly equal.  ·  Neutral (none): no direction - a question, background, or doubt whether AI is really the cause.";
const CHOICES_VAL = ["Alarming (minus)", "Reassuring (plus)", "Mixed", "Neutral / no direction (none)"];

const FRAGMENTS = __FRAGMENTS_JSON__;

// ---------------------------------------------------------------------
function buildForm() {
  if (!CODER || !CODER.trim()) throw new Error("Set CODER at the top of the script first.");
  const t0 = Date.now();
  const props = PropertiesService.getScriptProperties();
  const N = FRAGMENTS.length;

  // ---- open or create the form for this coder --------------------------
  let form;
  const formId = props.getProperty(propKey("formId"));
  if (formId) {
    form = FormApp.openById(formId);
    Logger.log("Resuming form for coder '%s' (id %s)", CODER, formId);
  } else {
    form = FormApp.create(FORM_TITLE + " — " + CODER);
    form.setDescription(INTRO)
        .setProgressBar(true)
        .setShowLinkToRespondAgain(false)
        .setAllowResponseEdits(false)
        .setLimitOneResponsePerUser(false)
        .setCollectEmail(false)
        .setConfirmationMessage("Thank you - your coding has been recorded. Please tell the researcher you have finished.");
    form.addTextItem().setTitle("Your name / coder ID").setRequired(true);
    const init = {};
    init[propKey("formId")] = form.getId();
    init[propKey("built")] = "0";
    init[propKey("wired")] = "0";
    props.setProperties(init);
    Logger.log("Created form '%s' (id %s)", form.getTitle(), form.getId());
  }

  const order = seededShuffle(range(N), hashStr(CODER));
  let built = parseInt(props.getProperty(propKey("built")) || "0", 10);

  // ---- pass 1: two pages per fragment (relevance page, valence page) -----
  while (built < N) {
    if (Date.now() - t0 > TIME_BUDGET_MS) {
      props.setProperty(propKey("built"), String(built));
      Logger.log("Paused: %s/%s fragments built (time budget). >>> Run buildForm again to continue.", built, N);
      return;
    }
    const f = FRAGMENTS[order[built]];
    const n = built + 1;

    form.addPageBreakItem()
        .setTitle("Fragment " + n + " of " + N)
        .setHelpText(f.text);
    form.addMultipleChoiceItem()
        .setTitle("[" + f.id + "] 1. Is this fragment relevant to \"AI affecting jobs\"?")
        .setHelpText(HELP_REL)
        .setChoiceValues(["Yes (1)", "No (0)"])   // navigation is wired in pass 2
        .setRequired(true);

    form.addPageBreakItem()
        .setTitle("Fragment " + n + " of " + N + " — valence")
        .setHelpText(f.text);
    form.addMultipleChoiceItem()
        .setTitle("[" + f.id + "] 2. What is the valence (direction)?")
        .setHelpText(HELP_VAL)
        .setChoiceValues(CHOICES_VAL)
        .setRequired(true);

    built++;
    if (built % 10 === 0) {
      props.setProperty(propKey("built"), String(built));
      Logger.log("built %s/%s", built, N);
    }
  }
  props.setProperty(propKey("built"), String(built));

  // ---- pass 2: skip logic — "No" jumps over this fragment's valence page --
  let wired = parseInt(props.getProperty(propKey("wired")) || "0", 10);
  if (wired < N) {
    const items = form.getItems();
    const pages = items.filter(i => i.getType() === FormApp.ItemType.PAGE_BREAK).map(i => i.asPageBreakItem());
    const qs = items.filter(i => i.getType() === FormApp.ItemType.MULTIPLE_CHOICE).map(i => i.asMultipleChoiceItem());
    if (pages.length !== 2 * N || qs.length !== 2 * N) {
      throw new Error("Form structure mismatch: " + pages.length + " pages, " + qs.length +
                      " questions (expected " + (2 * N) + " each). Run resetProgress(), move the form to Trash in Drive, then run buildForm again.");
    }
    // layout is [R0, V0, R1, V1, ...]: Yes -> CONTINUE (= V_k), No -> R_(k+1) (or SUBMIT on the last)
    while (wired < N) {
      if (Date.now() - t0 > TIME_BUDGET_MS) {
        props.setProperty(propKey("wired"), String(wired));
        Logger.log("Paused: %s/%s skip-links wired (time budget). >>> Run buildForm again to continue.", wired, N);
        return;
      }
      const qRel = qs[2 * wired];
      const nextRelPage = (wired + 1 < N) ? pages[2 * (wired + 1)] : null;
      const yes = qRel.createChoice("Yes (1)", FormApp.PageNavigationType.CONTINUE);
      const no = nextRelPage
        ? qRel.createChoice("No (0)", nextRelPage)
        : qRel.createChoice("No (0)", FormApp.PageNavigationType.SUBMIT);
      qRel.setChoices([yes, no]);
      wired++;
      if (wired % 25 === 0) {
        props.setProperty(propKey("wired"), String(wired));
        Logger.log("wired %s/%s", wired, N);
      }
    }
    props.setProperty(propKey("wired"), String(wired));
  }

  // ---- publish -----------------------------------------------------------
  try {
    if (typeof form.setPublished === "function") form.setPublished(true);   // newer Forms require an explicit publish
  } catch (e) {
    Logger.log("setPublished not available here (%s) — if the form shows 'not accepting responses', click Publish in the editor.", e);
  }
  form.setAcceptingResponses(true);

  Logger.log("DONE — coder '%s': %s fragments, %s pages, skip logic wired.", CODER, N, 2 * N);
  Logger.log("EDIT URL (yours):          %s", form.getEditUrl());
  Logger.log("RESPONDENT URL (send it):  %s", form.getPublishedUrl());
}

function status() {
  const p = PropertiesService.getScriptProperties();
  const id = p.getProperty(propKey("formId"));
  Logger.log("coder=%s  formId=%s  built=%s/%s  wired=%s/%s", CODER, id,
             p.getProperty(propKey("built")) || 0, FRAGMENTS.length,
             p.getProperty(propKey("wired")) || 0, FRAGMENTS.length);
  if (id) {
    const f = FormApp.openById(id);
    Logger.log("edit:    %s", f.getEditUrl());
    Logger.log("respond: %s", f.getPublishedUrl());
    Logger.log("responses so far: %s", f.getResponses().length);
  }
}

function resetProgress() {
  const p = PropertiesService.getScriptProperties();
  ["formId", "built", "wired"].forEach(k => p.deleteProperty(propKey(k)));
  Logger.log("Build state for coder '%s' cleared. Move the old form to Trash in Drive by hand, then run buildForm.", CODER);
}

// ---------------------------------------------------------------------
function propKey(k) { return "ws1_" + CODER + "_" + k; }

function range(n) { return Array.from({ length: n }, (_, i) => i); }

// same hash + LCG as ws1_survey.html -> identical order for the same coder name
function hashStr(s) {
  let h = 0;
  for (let i = 0; i < s.length; i++) { h = ((h << 5) - h + s.charCodeAt(i)) | 0; }
  return Math.abs(h);
}

function seededShuffle(arr, seed) {
  let s = seed;
  function rand() { s = (s * 1103515245 + 12345) & 0x7fffffff; return s / 0x7fffffff; }
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
